\c icapital_dev;

INSERT INTO accounts (username, email, password_hashed) VALUES 
('guest_account', 'guest_account@domain.com', 'hashed_password');

UPDATE accounts SET checking_account = 2815.00, savings_account = 7800.00, investments = 6000.00 WHERE username = 'guest_account';

INSERT INTO financial_transactions (account_id, transaction_type, amount, category, description, recurring, recurring_frequency, risk_level, is_planned, created_at) VALUES
(1, 'deposit', 5000.00, 'checking', 'Initial deposit into checking account', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'deposit', 3000.00, 'savings', 'Initial deposit into savings account', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'deposit', 2500.00, 'investment', 'Initial deposit into investments', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'income', 3000.00, 'salary', 'Monthly salary payment', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'income', 200.00, 'rental income', 'Rental income from property', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'income', 150.00, 'bonus', 'Performance bonus', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'income', 50.00, 'interest', 'Bank interest earned', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'income', 100.00, 'dividend', 'Dividend from investments', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 1000.00, 'rent/mortgage', 'Monthly rent payment', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'expense', 300.00, 'groceries', 'Monthly grocery shopping', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'expense', 150.00, 'utilities', 'Electricity and water bills', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'expense', 80.00, 'healthcare', 'Doctor visit', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 60.00, 'clothing', 'New clothing', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 50.00, 'entertainment', 'Movies', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 200.00, 'transportation', 'Gas and maintenance', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'expense', 120.00, 'subscriptions', 'Streaming services', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'expense', 40.00, 'dining', 'Dinner at a restaurant', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 30.00, 'household supplies', 'Cleaning products', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'investment', 500.00, 'retirement', 'Retirement fund contribution', FALSE, 'one-time', 'low', TRUE, NOW()),
(1, 'investment', 300.00, 'savings', 'Monthly savings', TRUE, 'monthly', 'low', TRUE, NOW()),
(1, 'investment', 200.00, 'investment', 'Stocks of tech company', FALSE, 'one-time', 'moderate', TRUE, NOW()),
(1, 'investment', 100.00, 'emergency fund', 'Emergency fund contribution', TRUE, 'monthly', 'low', TRUE, NOW()),
(1, 'income', 180.00, 'bonus', 'Quarterly bonus', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'expense', 90.00, 'education', 'Online course', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'investment', 250.00, 'investment', 'Real estate REITs', FALSE, 'one-time', 'moderate', TRUE, NOW()),
(1, 'expense', 70.00, 'entertainment', 'Concert tickets', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'income', 75.00, 'interest', 'Interest earned on savings', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 400.00, 'rent/mortgage', 'Additional rent payment', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'expense', 25.00, 'charity', 'Donation to local charity', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 45.00, 'travel', 'Bus ticket', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'investment', 600.00, 'retirement', 'IRA contribution', FALSE, 'one-time', 'low', TRUE, NOW()),
(1, 'income', 300.00, 'business income', 'Freelance project', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'expense', 220.00, 'utilities', 'Gas bill', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'expense', 90.00, 'subscriptions', 'Annual magazine subscription', FALSE, 'yearly', 'n/a', TRUE, NOW()),
(1, 'income', 500.00, 'salary', 'Side job salary', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'expense', 35.00, 'dining', 'Lunch with friends', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'investment', 400.00, 'investment', 'Tech startup shares', FALSE, 'one-time', 'high', TRUE, NOW()),
(1, 'expense', 180.00, 'education', 'Workshop on budgeting', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'expense', 50.00, 'groceries', 'Weekly groceries', TRUE, 'weekly', 'n/a', TRUE, NOW()),
(1, 'income', 90.00, 'interest', 'Interest earned on investments', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 300.00, 'transportation', 'Car maintenance', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'investment', 150.00, 'investment', 'Mutual fund investment', FALSE, 'one-time', 'moderate', TRUE, NOW()),
(1, 'expense', 120.00, 'clothing', 'New shoes', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 75.00, 'entertainment', 'Amusement park tickets', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 400.00, 'rent/mortgage', 'Rent for additional storage', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'income', 60.00, 'dividend', 'Quarterly dividend from stocks', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 200.00, 'household supplies', 'Furniture', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 100.00, 'healthcare', 'Prescription medication', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'investment', 250.00, 'savings', 'High-yield savings account', TRUE, 'monthly', 'low', TRUE, NOW()),
(1, 'income', 90.00, 'bonus', 'Holiday bonus', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'expense', 15.00, 'travel', 'Taxi fare', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'investment', 700.00, 'retirement', '401(k) contribution', TRUE, 'monthly', 'low', TRUE, NOW()),
(1, 'expense', 300.00, 'education', 'College course', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'expense', 80.00, 'subscriptions', 'Gym membership', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'income', 100.00, 'interest', 'Interest earned from bonds', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 500.00, 'rent/mortgage', 'Rent adjustment', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'expense', 55.00, 'dining', 'Coffee with colleagues', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'investment', 350.00, 'investment', 'Energy sector stocks', FALSE, 'one-time', 'moderate', TRUE, NOW()),
(1, 'expense', 40.00, 'travel', 'Uber ride', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 25.00, 'charity', 'Donation to children''s hospital', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 400.00, 'education', 'Textbooks for class', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'expense', 200.00, 'healthcare', 'Dental checkup', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'income', 150.00, 'business income', 'Sold handmade crafts', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'expense', 75.00, 'clothing', 'Winter coat', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 85.00, 'entertainment', 'Music concert', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'income', 300.00, 'rental income', 'Rent from storage space', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'expense', 25.00, 'groceries', 'Weekly groceries', TRUE, 'weekly', 'n/a', TRUE, NOW()),
(1, 'expense', 65.00, 'subscriptions', 'Online software subscription', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'investment', 500.00, 'investment', 'Cryptocurrency', FALSE, 'one-time', 'high', TRUE, NOW()),
(1, 'expense', 120.00, 'dining', 'Dinner with family', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 400.00, 'rent/mortgage', 'Home rent', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'income', 250.00, 'dividend', 'Dividend from investment fund', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 90.00, 'household supplies', 'Vacuum cleaner', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 70.00, 'healthcare', 'Eyeglasses', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'income', 450.00, 'salary', 'Freelance project completion', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'investment', 150.00, 'retirement', 'Roth IRA contribution', FALSE, 'one-time', 'low', TRUE, NOW()),
(1, 'expense', 30.00, 'education', 'Online tutorial', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'expense', 200.00, 'travel', 'Flight ticket', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'investment', 1000.00, 'savings', 'Saving for new car', TRUE, 'monthly', 'low', TRUE, NOW()),
(1, 'expense', 150.00, 'transportation', 'Car insurance', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'expense', 35.00, 'dining', 'Café breakfast', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'income', 60.00, 'bonus', 'Performance incentive', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'expense', 180.00, 'utilities', 'Internet bill', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'expense', 300.00, 'household supplies', 'New furniture', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'income', 75.00, 'interest', 'Savings account interest', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'investment', 250.00, 'investment', 'Gold ETF', FALSE, 'one-time', 'low', TRUE, NOW()),
(1, 'expense', 400.00, 'rent/mortgage', 'Rental payment', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'expense', 55.00, 'clothing', 'New workout gear', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 65.00, 'travel', 'Airport shuttle', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 200.00, 'utilities', 'Electric bill', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'expense', 20.00, 'charity', 'Food bank donation', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 350.00, 'education', 'Professional certification', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'income', 500.00, 'salary', 'Part-time work', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'investment', 200.00, 'investment', 'Corporate bonds', FALSE, 'one-time', 'moderate', TRUE, NOW()),
(1, 'expense', 50.00, 'entertainment', 'Subscription to online games', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'expense', 40.00, 'dining', 'Dinner with a friend', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'income', 250.00, 'bonus', 'Quarterly team performance bonus', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'income', 500.00, 'rental income', 'Rental income for commercial property', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'income', 120.00, 'interest', 'Interest earned from savings bonds', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'income', 400.00, 'business income', 'Freelance consulting fee', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'income', 220.00, 'dividend', 'Dividend earned from mutual funds', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'expense', 150.00, 'groceries', 'Monthly grocery purchase', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'expense', 300.00, 'rent/mortgage', 'Partial rent payment', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'expense', 250.00, 'transportation', 'Car repair service', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'expense', 200.00, 'education', 'Books for self-improvement', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'expense', 75.00, 'entertainment', 'Theater tickets', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 65.00, 'clothing', 'New casual wear', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 110.00, 'healthcare', 'Routine dental checkup', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 50.00, 'subscriptions', 'Monthly newspaper subscription', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'expense', 30.00, 'household supplies', 'Basic cleaning materials', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 40.00, 'charity', 'Donation to a local charity', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 100.00, 'travel', 'Day trip expenses', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 250.00, 'rent/mortgage', 'Shared apartment rent', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'investment', 450.00, 'investment', 'Investing in healthcare stocks', FALSE, 'one-time', 'moderate', TRUE, NOW()),
(1, 'investment', 500.00, 'retirement', 'Contribution to retirement savings', TRUE, 'monthly', 'low', TRUE, NOW()),
(1, 'investment', 300.00, 'savings', 'High-yield savings account deposit', TRUE, 'monthly', 'low', TRUE, NOW()),
(1, 'investment', 350.00, 'investment', 'Cryptocurrency investment', FALSE, 'one-time', 'high', TRUE, NOW()),
(1, 'investment', 150.00, 'savings', 'Emergency savings fund contribution', TRUE, 'monthly', 'low', TRUE, NOW()),
(1, 'investment', 250.00, 'retirement', 'IRA contribution for the year', FALSE, 'one-time', 'low', TRUE, NOW()),
(1, 'investment', 100.00, 'investment', 'Investment in tech startup', FALSE, 'one-time', 'high', TRUE, NOW()),
(1, 'income', 200.00, 'bonus', 'Project completion bonus', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'expense', 45.00, 'travel', 'Fuel costs for weekend drive', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 30.00, 'dining', 'Dinner with family', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 100.00, 'groceries', 'Grocery shopping', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'expense', 25.00, 'household supplies', 'Replacement batteries', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'income', 150.00, 'dividend', 'Dividend from energy sector', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'expense', 80.00, 'subscriptions', 'Online video platform subscription', TRUE, 'monthly', 'n/a', TRUE, NOW()),
(1, 'expense', 35.00, 'healthcare', 'First aid supplies', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'investment', 300.00, 'investment', 'Mutual funds purchase', FALSE, 'one-time', 'moderate', TRUE, NOW()),
(1, 'income', 500.00, 'business income', 'Freelance design work', FALSE, 'one-time', 'n/a', TRUE, NOW()),
(1, 'expense', 70.00, 'clothing', 'Work attire', FALSE, 'one-time', 'n/a', FALSE, NOW()),
(1, 'expense', 150.00, 'education', 'Online programming course', FALSE, 'one-time', 'n/a', TRUE, NOW());